using Microsoft.AspNetCore.Http;
using PrinterApp.Services.Interfaces;
using System.Text;


namespace PrinterApp.Services.Implementations;

public class LanguageService : ILanguageService
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private const string SessionKey = "AppLanguage";
    private const string DefaultLanguage = "ar";

    // Arabic Translations
    private readonly Dictionary<string, string> _arabicTexts = new()
    {
        // في _arabicTexts:
        ["LoginSuccessful"] = "تم تسجيل الدخول بنجاح",
        ["InvalidLoginAttempt"] = "محاولة تسجيل دخول غير صالحة",
        ["RegistrationSuccessful"] = "تم التسجيل بنجاح",
        ["LogoutSuccessful"] = "تم تسجيل الخروج بنجاح",
        // في _arabicTexts أضف:
        ["WelcomeBack"] = "أهلاً بعودتك! الرجاء تسجيل الدخول",
        ["Email"] = "البريد الإلكتروني",
        ["EnterEmail"] = "أدخل بريدك الإلكتروني",
        ["Password"] = "كلمة المرور",
        ["EnterPassword"] = "أدخل كلمة المرور",
        ["RememberMe"] = "تذكرني",
        ["DontHaveAccount"] = "ليس لديك حساب؟",
        ["RegisterHere"] = "سجل هنا",
        ["CreateNewAccount"] = "إنشاء حساب جديد",
        ["FullName"] = "الاسم الكامل",
        ["EnterFullName"] = "أدخل اسمك الكامل",
        ["ConfirmPassword"] = "تأكيد كلمة المرور",
        ["ReenterPassword"] = "أعد إدخال كلمة المرور",
        ["AlreadyHaveAccount"] = "لديك حساب بالفعل؟",
        ["LoginHere"] = "سجل دخول هنا",
        // في _arabicTexts أضف:
        ["Users"] = "المستخدمين",
        ["Permissions"] = "الصلاحيات",
        ["Welcome"] = "مرحباً",
        ["Logout"] = "تسجيل الخروج",
        ["Register"] = "تسجيل جديد",
        ["AllRightsReserved"] = "جميع الحقوق محفوظة",
        ["Materials"] = "المواد",
        ["Production"] = "الإنتاج",
        ["RollDirections"] = "اتجاهات اللف",
        // Navigation
        ["Home"] = "الرئيسية",
        ["Dashboard"] = "لوحة التحكم",
        ["Machines"] = "الماكينات",
        ["MoldShapes"] = "أشكال القوالب",
        ["Molds"] = "القوالب",
        ["Cores"] = "الكور",
        ["Settings"] = "الإعدادات",

        // Common
        ["Search"] = "بحث",
        ["SearchPlaceholder"] = "ابحث بالاسم أو الوصف",
        ["Reset"] = "إعادة تعيين",
        ["AddNew"] = "إضافة جديد",
        ["Create"] = "إنشاء",
        ["Edit"] = "تعديل",
        ["Delete"] = "حذف",
        ["Cancel"] = "إلغاء",
        ["Save"] = "حفظ",
        ["SaveChanges"] = "حفظ التغييرات",
        ["BackToList"] = "العودة للقائمة",
        ["Actions"] = "الإجراءات",
        ["Status"] = "الحالة",
        ["Active"] = "نشط",
        ["Inactive"] = "غير نشط",
        ["IsActive"] = "نشط",
        ["Activate"] = "تفعيل",
        ["Deactivate"] = "تعطيل",
        ["Description"] = "الوصف",
        ["CreatedDate"] = "تاريخ الإنشاء",
        ["LastModified"] = "آخر تعديل",
        ["NoResultsFound"] = "لا توجد نتائج",
        ["NoDataAvailable"] = "لا توجد بيانات متاحة",
        ["DeleteConfirmation"] = "هل أنت متأكد من حذف هذا السجل؟",
        ["TotalRecords"] = "إجمالي السجلات",
        ["ActiveRecords"] = "السجلات النشطة",
        ["Optional"] = "اختياري",
        ["AutoCalculated"] = "يتم الحساب تلقائياً",
        ["Statistics"] = "الإحصائيات",
        ["ImagePreview"] = "معاينة الصورة",
        ["CurrentImage"] = "الصورة الحالية",
        ["UploadImage"] = "رفع صورة",
        ["ChangeImage"] = "تغيير الصورة",

        // Machines
        ["Machine"] = "ماكينة",
        ["MachineManagement"] = "إدارة الماكينات",
        ["MachineName"] = "اسم الماكينة",
        ["MachineCode"] = "كود الماكينة",
        ["SelectMachine"] = "اختر الماكينة",

        // Mold Shapes
        ["MoldShape"] = "شكل القالب",
        ["MoldShapeManagement"] = "إدارة أشكال القوالب",
        ["MoldShapeName"] = "اسم شكل القالب",
        ["ShapeImage"] = "صورة الشكل",
        ["MoldsCount"] = "عدد القوالب",
        ["SelectMoldShape"] = "اختر شكل القالب",

        // Molds
        ["MoldManagement"] = "إدارة القوالب",
        ["MoldNumber"] = "رقم القالب",
        ["Width"] = "العرض",
        ["Height"] = "الارتفاع",
        ["TotalEyes"] = "إجمالي العيون",
        ["PrintedSize"] = "مقاس الخام المطبوع",
        ["PlainSize"] = "مقاس الخام السادة",

        // Cores
        ["CoreManagement"] = "إدارة الكور",
        ["CoreName"] = "اسم الكور",
        ["CoreCoefficient"] = "معامل الكور",
        ["WidthCor"] = "عرض الكور",
        ["HeightCor"] = "ارتفاع الكور",

        // في _arabicTexts أضف:
        ["Welcome"] = "مرحباً بك في تطبيق المطبعة",
        ["WelcomeMessage"] = "نظام إدارة شامل لعمليات المطبعة",
        ["ManageCores"] = "إدارة الكور والأبعاد",
        ["ManageCartons"] = "إدارة الكراتين والتغليف",
        ["ManageKnives"] = "إدارة السكاكين والأسعار",
        ["ManageSuppliers"] = "إدارة الموردين والاتصال",
        ["ManageRawMaterials"] = "إدارة المواد الخام والأسعار",
        ["ManageProducts"] = "إدارة الأصناف والتفاصيل",
        ["ManageAdditions"] = "إدارة إضافات التصنيع",
        ["ManageMachines"] = "إدارة الماكينات والصيانة",
        ["PleaseLoginMessage"] = "الرجاء تسجيل الدخول للوصول إلى النظام",
        ["Login"] = "تسجيل الدخول",
        ["Cartons"] = "الكراتين",
        ["Knives"] = "السكاكين",
        ["Suppliers"] = "الموردين",
        ["RawMaterials"] = "المواد الخام",
        ["Products"] = "الأصناف",
        ["Additions"] = "الإضافات",

        // في _arabicTexts:
        ["LastName"] = "اسم العائلة",
        ["EnterLastName"] = "أدخل اسم العائلة",

        // في _arabicTexts أضف:
        ["TotalCartons"] = "إجمالي الكراتين",
        ["ActiveCartons"] = "الكراتين النشطة",
        ["InactiveCartons"] = "الكراتين غير النشطة",
        ["AverageFactor"] = "متوسط المعامل",
        ["CartonName"] = "اسم الكرتونة",
        ["CartonFactor"] = "معامل الكرتونة",
        ["ClearSearch"] = "مسح البحث",
        ["SearchingFor"] = "البحث عن",
        ["Found"] = "وجدنا",
        ["Results"] = "نتيجة",
        ["NoCartonsAvailable"] = "لا توجد كراتين متاحة",
        ["TryAdjustingSearch"] = "حاول تعديل معايير البحث",
        ["StartByAddingCarton"] = "ابدأ بإضافة أول كرتونة",
        // في _arabicTexts أضف:
        ["CreateCarton"] = "إنشاء كرتونة",
        ["CreateNewCarton"] = "إنشاء كرتونة جديدة",
        ["CartonInformation"] = "معلومات الكرتونة",
        ["EnterCartonName"] = "أدخل اسم الكرتونة (مثال: كرتونة قياسية A)",
        ["CartonNameMustBeUnique"] = "يجب أن يكون اسم الكرتونة فريداً",
        ["EnterCartonFactor"] = "أدخل معامل الكرتونة (مثال: 1.25)",
        ["CartonFactorDescription"] = "معامل الضرب لهذا النوع من الكراتين",
        ["EnterDescriptionOptional"] = "أدخل الوصف (اختياري)",
        ["TipsForAddingCartons"] = "نصائح لإضافة الكراتين",
        ["UseDescriptiveNames"] = "استخدم أسماء وصفية لسهولة التعرف",
        ["CartonFactorUsedInCalculations"] = "يُستخدم معامل الكرتونة في الحسابات (مشابه لمعامل الكور)",
        ["CommonFactorsRange"] = "المعاملات الشائعة تتراوح من 0.5 إلى 3.0",
        ["HigherFactorMeans"] = "المعامل الأعلى يعني كراتين أكبر/أثقل",
        // في _arabicTexts أضف:
        ["EditCarton"] = "تعديل الكرتونة",
        ["CartonIsActive"] = "الكرتونة نشطة",
        ["Created"] = "تم الإنشاء",
        // في _arabicTexts أضف:
        ["SearchCoresPlaceholder"] = "ابحث بالاسم، المعامل، العرض، أو الارتفاع...",
        ["TotalCores"] = "إجمالي الكور",
        ["ActiveCores"] = "الكور النشط",
        ["InactiveCores"] = "الكور غير النشط",
        ["NoCoresAvailable"] = "لا توجد كور متاحة",
        ["StartByAddingCore"] = "ابدأ بإضافة أول كور",

        // في _arabicTexts أضف:
        ["CreateCore"] = "إنشاء كور",
        ["CreateNewCore"] = "إنشاء كور جديد",
        ["CoreInformation"] = "معلومات الكور",
        ["EnterCoreName"] = "أدخل اسم الكور (مثال: كور صغير، كور كبير)",
        ["EnterCoefficientValue"] = "أدخل قيمة المعامل",
        ["CoreCoefficientHelp"] = "يُستخدم معامل الكور في الحسابات (مثال: 0.5, 1.25, 2.0)",
        ["WidthInMm"] = "العرض بالملم",
        ["HeightInMm"] = "الارتفاع بالملم",
        // في _arabicTexts أضف:
        ["EditCore"] = "تعديل الكور",
        ["CoreCoefficientUsedForCalculations"] = "يُستخدم معامل الكور في الحسابات",
        ["CoreIsActive"] = "الكور نشط",

        // في _arabicTexts أضف:
        ["Coefficient"] = "المعامل",
        ["Width"] = "العرض",
        ["Height"] = "الارتفاع",
        ["DeleteCoreConfirmation"] = "هل أنت متأكد من حذف هذا الكور؟",

        // في _arabicTexts أضف:
        ["CreateKnife"] = "إنشاء سكين",
        ["CreateNewKnife"] = "إنشاء سكين جديد",
        ["KnifeInformation"] = "معلومات السكين",
        ["KnifeName"] = "اسم السكين",
        ["EnterKnifeName"] = "أدخل اسم السكين (مثال: شفرة قياسية 10 ملم)",
        ["KnifeNameMustBeUnique"] = "يجب أن يكون اسم السكين فريداً",
        ["KnifeFactor"] = "معامل السكين",
        ["EnterKnifeFactor"] = "أدخل معامل السكين (مثال: 1.15)",
        ["KnifeFactorDescription"] = "معامل الضرب لهذا النوع من السكاكين",
        ["TipsForAddingKnives"] = "نصائح لإضافة السكاكين",
        ["UseDescriptiveNamesWithBladeSize"] = "استخدم أسماء وصفية تتضمن حجم الشفرة إن أمكن",
        ["KnifeFactorUsedInCuttingCalculations"] = "يُستخدم معامل السكين في حسابات القطع",
        ["CommonKnifeFactorsRange"] = "المعاملات الشائعة تتراوح من 0.8 إلى 2.0",
        ["HigherFactorMeansThickerBlades"] = "المعامل الأعلى يعني شفرات أكثر سمكاً/حدة",
        ["CreateKnife"] = "إنشاء السكين",

        // في _arabicTexts أضف:
        ["EditKnife"] = "تعديل السكين",
        ["KnifeIsActive"] = "السكين نشط",

        // في _arabicTexts أضف:
        ["KnivesManagement"] = "إدارة السكاكين",
        ["AddNewKnife"] = "إضافة سكين جديد",
        ["SearchKnivesPlaceholder"] = "ابحث باسم السكين، المعامل، أو الوصف...",
        ["TotalKnives"] = "إجمالي السكاكين",
        ["ActiveKnives"] = "السكاكين النشطة",
        ["InactiveKnives"] = "السكاكين غير النشطة",
        ["AverageFactor"] = "متوسط المعامل",
        ["DeleteKnifeConfirmation"] = "هل أنت متأكد من حذف هذا السكين؟",
        ["NoKnivesAvailable"] = "لا توجد سكاكين متاحة",
        ["StartByAddingKnife"] = "ابدأ بإضافة أول سكين",

        // في _arabicTexts أضف:
        ["MachinesManagement"] = "إدارة الآلات",
        ["AddNewMachine"] = "إضافة آلة جديدة",
        ["SearchMachinesPlaceholder"] = "ابحث بالاسم، الموديل، الشركة المصنعة، أو العرض الأقصى...",
        ["TotalMachines"] = "إجمالي الآلات",
        ["ActiveMachines"] = "الآلات النشطة",
        ["InactiveMachines"] = "الآلات غير النشطة",
        ["MaxWidthMm"] = "العرض الأقصى (ملم)",
        ["MachineName"] = "اسم الآلة",
        ["ModelNumber"] = "رقم الموديل",
        ["Manufacturer"] = "الشركة المصنعة",
        ["DeleteMachineConfirmation"] = "هل أنت متأكد من حذف هذه الآلة؟",
        ["NoMachinesAvailable"] = "لا توجد آلات متاحة",
        ["StartByAddingMachine"] = "ابدأ بإضافة أول آلة",

        // في _arabicTexts أضف:
        ["CreateMachine"] = "إنشاء آلة",
        ["CreateNewMachine"] = "إنشاء آلة جديدة",
        ["MachineInformation"] = "معلومات الآلة",
        ["EnterMachineName"] = "أدخل اسم الآلة (مثال: HP Indigo 7600)",
        ["MaxWidth"] = "العرض الأقصى",
        ["EnterMaximumWidth"] = "أدخل العرض الأقصى",
        ["MaxWidthHelp"] = "العرض الأقصى للطباعة لهذه الآلة بالمليمترات",
        ["ModelNumberPlaceholder"] = "مثال: XR-2000",
        ["ManufacturerPlaceholder"] = "مثال: HP, Canon, Epson",
        ["MachineDescriptionPlaceholder"] = "أدخل وصف الآلة، المواصفات، أو الملاحظات (اختياري)",
        ["TipsForAddingMachines"] = "نصائح لإضافة الآلات",
        ["UseDescriptiveMachineNames"] = "استخدم أسماء وصفية تحدد الآلة بسهولة",
        ["EnsureMaxWidthAccurate"] = "تأكد من دقة العرض الأقصى للحسابات الصحيحة",
        ["IncludeModelNumberForReference"] = "أضف رقم الموديل للرجوع إليه مستقبلاً",
        ["AddSpecialNotesInDescription"] = "أضف أي ملاحظات خاصة عن الآلة في الوصف",
        ["CreateMachine"] = "إنشاء الآلة",

        // في _arabicTexts أضف:
        ["EditMachine"] = "تعديل الآلة",
        ["MachineIsActive"] = "الآلة نشطة",
        ["InactiveMachinesNotAvailable"] = "الآلات غير النشطة لن تكون متاحة للاختيار في عمليات الطباعة",
        // في _arabicTexts أضف:
        ["ManufacturingAdditionsManagement"] = "إدارة الإضافات التصنيعية",
        ["AddNewAddition"] = "إضافة إضافة جديدة",
        ["SearchAdditionsPlaceholder"] = "ابحث باسم الإضافة...",
        ["TotalAdditions"] = "إجمالي الإضافات",
        ["ActiveAdditions"] = "الإضافات النشطة",
        ["InactiveAdditions"] = "الإضافات غير النشطة",
        ["AdditionName"] = "اسم الإضافة",
        ["DeleteAdditionConfirmation"] = "هل أنت متأكد من حذف هذه الإضافة؟",
        ["NoAdditionsAvailable"] = "لا توجد إضافات تصنيعية متاحة",
        ["StartByAddingAddition"] = "ابدأ بإضافة أول إضافة تصنيعية",
        // في _arabicTexts أضف:
        ["CreateManufacturingAddition"] = "إنشاء إضافة تصنيعية",
        ["CreateNewManufacturingAddition"] = "إنشاء إضافة تصنيعية جديدة",
        ["ManufacturingAdditionInformation"] = "معلومات الإضافة التصنيعية",
        ["BasicInformation"] = "المعلومات الأساسية",
        ["EnterAdditionName"] = "أدخل اسم الإضافة (مثال: تغليف، طلاء UV، قص)",
        ["AdditionNameMustBeUnique"] = "يجب أن يكون اسم الإضافة فريداً",
        ["ExamplesOfManufacturingAdditions"] = "أمثلة على الإضافات التصنيعية",
        ["AdditionExample1"] = "كليشة",
        ["AdditionExample2"] = "شغيلة",
        ["ImportantNotes"] = "ملاحظات مهمة",
        ["UseClearDescriptiveNames"] = "استخدم أسماء واضحة ووصفية للإضافات",
        ["AdditionsEnhanceProductQuality"] = "يمكن استخدام الإضافات لتحسين جودة المنتج",
        ["CanActivateDeactivateAnytime"] = "يمكنك تفعيل/تعطيل الإضافات في أي وقت",
        ["InactiveAdditionsNotAvailable"] = "الإضافات غير النشطة لن تكون متاحة للاختيار",
        ["CreateAddition"] = "إنشاء الإضافة",

        // في _arabicTexts أضف:
        ["EditManufacturingAddition"] = "تعديل الإضافة التصنيعية",
        ["AdditionIsActive"] = "الإضافة نشطة",
        ["InactiveAdditionsNotAvailableForOrders"] = "الإضافات غير النشطة لن تكون متاحة للاختيار في الطلبات",
        ["CommonManufacturingAdditions"] = "الإضافات التصنيعية الشائعة",

        // في _arabicTexts أضف:
        ["Molds"] = "القوالب",
        ["MoldManagement"] = "إدارة القوالب",
        ["SearchMoldsPlaceholder"] = "ابحث بالاسم أو الوصف",
        ["TotalMolds"] = "إجمالي القوالب",
        ["ActiveMolds"] = "القوالب النشطة",
        ["TotalEyes"] = "إجمالي العيون",
        ["NoMoldsAvailable"] = "لا توجد قوالب متاحة",
        ["StartByAddingMold"] = "ابدأ بإضافة أول قالب",

        // في _arabicTexts أضف:
        ["CreateMold"] = "إنشاء قالب",
        ["MoldInformation"] = "معلومات القالب",
        ["MoldNumber"] = "رقم القالب",
        ["EnterMoldNumber"] = "أدخل رقم القالب",
        ["MoldShape"] = "شكل القالب",
        ["SelectMoldShape"] = "اختر شكل القالب",
        ["EnterWidth"] = "أدخل العرض",
        ["EnterHeight"] = "أدخل الارتفاع",
        ["AutoCalculated"] = "محسوب تلقائياً",
        ["PrintedRawMaterialSize"] = "حجم المادة الخام المطبوعة",
        ["PlainRawMaterialSize"] = "حجم المادة الخام العادية",
        ["EnterDescription"] = "أدخل الوصف",
        ["CalculationFormula"] = "صيغة الحساب",
        ["TotalEyesFormula"] = "إجمالي العيون = العرض × الارتفاع (يتم الحساب تلقائياً عند إدخال القيم)",

        // في _arabicTexts أضف:
        ["EditMold"] = "تعديل القالب",
        ["MoldIsActive"] = "القالب نشط",
        ["InactiveMoldsNotAvailable"] = "القوالب غير النشطة لن تكون متاحة للاختيار",


        // في _arabicTexts أضف:
        ["PrintedSize"] = "حجم المطبوع",
        ["PlainSize"] = "حجم العادي",
        ["DeleteMoldConfirmation"] = "هل أنت متأكد من حذف هذا القالب؟",
        // في _arabicTexts أضف:
        ["MoldShapes"] = "أشكال القوالب",
        ["MoldShapeManagement"] = "إدارة أشكال القوالب",
        ["SearchMoldShapesPlaceholder"] = "ابحث باسم الشكل",
        ["TotalMoldShapes"] = "إجمالي الأشكال",
        ["ActiveMoldShapes"] = "الأشكال النشطة",
        ["NoMoldShapesAvailable"] = "لا توجد أشكال قوالب متاحة",
        ["StartByAddingMoldShape"] = "ابدأ بإضافة أول شكل قالب",

        // في _arabicTexts أضف:
        ["CreateMoldShape"] = "إنشاء شكل قالب",
        ["MoldShapeInformation"] = "معلومات شكل القالب",
        ["MoldShapeName"] = "اسم شكل القالب",
        ["EnterMoldShapeName"] = "أدخل اسم شكل القالب",
        ["ShapeImage"] = "صورة الشكل",
        ["ImageFormatInfo"] = "الصيغ المسموحة: JPG, JPEG, PNG, GIF, BMP (الحد الأقصى: 5 ميجابايت)",
        ["ImagePreview"] = "معاينة الصورة",
        ["MoldShapeNameMustBeUnique"] = "يجب أن يكون اسم شكل القالب فريداً",
        ["ShapeImageHelpsIdentification"] = "الصورة تساعد في تحديد الشكل بسهولة",
        ["DescriptionIsOptionalButRecommended"] = "الوصف اختياري ولكن يُنصح به",

        // في _arabicTexts أضف:
        ["EditMoldShape"] = "تعديل شكل القالب",
        ["CurrentImage"] = "الصورة الحالية",
        ["UploadImage"] = "رفع صورة",
        ["ChangeImage"] = "تغيير الصورة",
        ["LeaveEmptyToKeepCurrentImage"] = "اتركه فارغاً للاحتفاظ بالصورة الحالية. الصيغ المسموحة: JPG, JPEG, PNG, GIF, BMP (الحد الأقصى: 5 ميجابايت)",
        ["NewImagePreview"] = "معاينة الصورة الجديدة",
        ["MoldShapeIsActive"] = "شكل القالب نشط",
        ["InactiveMoldShapesNotAvailable"] = "أشكال القوالب غير النشطة لن تكون متاحة للاختيار",
        ["ThisMoldShapeUsedIn"] = "يُستخدم شكل القالب هذا في",

        // في _arabicTexts أضف:
        ["MoldsCount"] = "عدد القوالب",
        ["NoDescription"] = "لا يوجد وصف",
        ["DeleteMoldShapeConfirmation"] = "هل أنت متأكد من حذف شكل القالب هذا؟",
        ["CannotDeleteHasMolds"] = "لا يمكن الحذف - مرتبط بـ",

        // في _arabicTexts أضف:
        ["Permissions"] = "الصلاحيات",
        ["PermissionsManagement"] = "إدارة الصلاحيات",
        ["CreateNewPermission"] = "إنشاء صلاحية جديدة",
        ["PermissionName"] = "اسم الصلاحية",
        ["Code"] = "الرمز",
        ["ManageRoles"] = "إدارة الأدوار",
        ["Roles"] = "الأدوار",
        ["DeletePermissionConfirmation"] = "هل أنت متأكد من حذف هذه الصلاحية؟",
        ["NoPermissionsFound"] = "لا توجد صلاحيات",
        ["CreateFirstPermissionToGetStarted"] = "أنشئ أول صلاحية للبدء",
        ["CreatePermission"] = "إنشاء صلاحية",

        // في _arabicTexts أضف:
        ["PermissionDetails"] = "تفاصيل الصلاحية",
        ["PermissionNamePlaceholder"] = "مثال: عرض المستخدمين، تعديل المنشورات",
        ["PermissionCode"] = "رمز الصلاحية",
        ["PermissionCodePlaceholder"] = "مثال: VIEW_USERS, EDIT_POSTS",
        ["PermissionCodeHint"] = "استخدم أحرف كبيرة وشرطة سفلية فقط (مثال: MANAGE_USERS)",
        ["PermissionDescriptionPlaceholder"] = "صف ما تسمح هذه الصلاحية للمستخدمين بفعله...",
        ["PermissionNameShouldBeClear"] = "يجب أن يكون اسم الصلاحية واضحاً ووصفياً",
        ["PermissionCodeMustBeUnique"] = "يجب أن يكون رمز الصلاحية فريداً في النظام",
        ["UseUppercaseForCode"] = "استخدم أحرفاً كبيرة وشرطة سفلية للرمز",
        ["DescriptionHelpsUnderstandPermission"] = "الوصف يساعد في فهم الغرض من الصلاحية",

        // في _arabicTexts أضف:
        ["EditPermission"] = "تعديل الصلاحية",
        ["UpdatePermissionDetails"] = "تحديث تفاصيل الصلاحية",
        ["Warning"] = "تحذير",
        ["ChangePermissionCodeWarning"] = "تغيير رمز الصلاحية قد يؤثر على الأنظمة والأدوار التي تستخدم هذه الصلاحية. تأكد من تحديث جميع المراجع المتعلقة بها.",

        // في _arabicTexts أضف:
        ["ProductsManagement"] = "إدارة المنتجات",
        ["AddNewProduct"] = "إضافة منتج جديد",
        ["SearchProductsPlaceholder"] = "ابحث باسم المنتج، الكود، المورد، أو المادة الخام",
        ["TotalProducts"] = "إجمالي المنتجات",
        ["ActiveProducts"] = "المنتجات النشطة",
        ["PrintedProducts"] = "المنتجات المطبوعة",
        ["NonPrintedProducts"] = "المنتجات غير المطبوعة",
        ["ProductCode"] = "كود المنتج",
        ["ProductName"] = "اسم المنتج",
        ["Type"] = "النوع",
        ["Supplier"] = "المورد",
        ["RawMaterial"] = "المادة الخام",
        ["Additions"] = "الإضافات",
        ["Printed"] = "مطبوع",
        ["NonPrinted"] = "غير مطبوع",
        ["None"] = "لا يوجد",
        ["DeleteProductConfirmation"] = "هل أنت متأكد من حذف هذا المنتج؟",
        ["NoProductsFound"] = "لم يتم العثور على منتجات",
        ["NoProductsAvailable"] = "لا توجد منتجات متاحة",
        ["StartByAddingProduct"] = "ابدأ بإضافة أول منتج",
        // في _arabicTexts أضف:
        ["CreateProduct"] = "إنشاء منتج",
        ["CreateNewProduct"] = "إنشاء منتج جديد",
        ["ProductInformation"] = "معلومات المنتج",
        ["BasicInformation"] = "المعلومات الأساسية",
        ["ProductNamePlaceholder"] = "أدخل اسم المنتج (مثال: علبة هدايا فاخرة)",
        ["SelectSupplier"] = "اختر المورد",
        ["WillBeAutoGenerated"] = "سيتم توليده تلقائياً",
        ["GenerateCode"] = "توليد الكود",
        ["ProductCodeFormat"] = "الصيغة: كود المورد + 01, 02, 03...",
        ["ProductTypeAndMaterial"] = "نوع المنتج والمادة الخام",
        ["ProductType"] = "نوع المنتج",
        ["SelectRawMaterial"] = "اختر المادة الخام",
        ["SelectManufacturingAdditionsHint"] = "اختر جميع الإضافات التصنيعية التي تنطبق على هذا المنتج",
        ["NoManufacturingAdditionsAvailable"] = "لا توجد إضافات تصنيعية متاحة. الرجاء إضافة إضافات أولاً.",
        ["AddManufacturingAddition"] = "إضافة إضافة تصنيعية",
        ["DescriptionOptional"] = "الوصف (اختياري)",
        ["ProductDescriptionPlaceholder"] = "أدخل وصف المنتج، ملاحظات، أو المواصفات...",
        ["ExampleProductCodeGeneration"] = "مثال على توليد كود المنتج",
        ["ProductCodeExample1"] = "إذا كان كود المورد SUP، ستكون أكواد المنتجات: SUP01, SUP02, SUP03...",
        ["ProductCodeExample2"] = "إذا كان كود المورد ABC، ستكون أكواد المنتجات: ABC01, ABC02, ABC03...",
        ["ProductCodeExample3"] = "النظام يولد الرقم التالي المتاح تلقائياً",
        ["ProductCodeExample4"] = "أكواد المنتجات فريدة ولا يمكن تكرارها",
        ["CreateProduct"] = "إنشاء المنتج",
        ["PleaseSelectSupplierFirst"] = "الرجاء اختيار مورد أولاً",
        ["Generating"] = "جاري التوليد",
        ["CodeGenerated"] = "تم توليد الكود",
        ["ErrorGeneratingProductCode"] = "خطأ في توليد كود المنتج",
        // في _arabicTexts أضف:
        ["EditProduct"] = "تعديل المنتج",
        ["EnterProductName"] = "أدخل اسم المنتج",
        ["ProductCodeCannotBeChanged"] = "لا يمكن تغيير كود المنتج بعد الإنشاء",
        ["ProductIsActive"] = "المنتج نشط",
        ["InactiveProductsNotAvailable"] = "المنتجات غير النشطة لن تكون متاحة للاختيار في الطلبات",
        ["At"] = "في",

        // في _arabicTexts أضف:
        ["RawMaterialsManagement"] = "إدارة المواد الخام",
        ["AddNewRawMaterial"] = "إضافة مادة خام جديدة",
        ["SearchRawMaterialsPlaceholder"] = "ابحث بالاسم، العرض، الارتفاع، أو السعر",
        ["TotalMaterials"] = "إجمالي المواد",
        ["ActiveMaterials"] = "المواد النشطة",
        ["InactiveMaterials"] = "المواد غير النشطة",
        ["MaterialName"] = "اسم المادة",
        ["WidthCm"] = "العرض (م)",
        ["HeightM"] = "الارتفاع (م)",
        ["AreaM2"] = "المساحة (م²)",
        ["PricePerM2"] = "السعر/م²",
        ["PricePerM"] = "السعر/م",
        ["Cm"] = "سم",
        ["M"] = "م",
        ["M2"] = "م²",
        ["DeleteRawMaterialConfirmation"] = "هل أنت متأكد من حذف هذه المادة الخام؟",
        ["NoRawMaterialsFound"] = "لم يتم العثور على مواد خام",
        ["NoRawMaterialsAvailable"] = "لا توجد مواد خام متاحة",
        ["StartByAddingRawMaterial"] = "ابدأ بإضافة أول مادة خام",

        // في _arabicTexts أضف:
        ["CreateRawMaterial"] = "إنشاء مادة خام",
        ["CreateNewRawMaterial"] = "إنشاء مادة خام جديدة",
        ["RawMaterialInformation"] = "معلومات المادة الخام",
        ["RawMaterialName"] = "اسم المادة الخام",
        ["RawMaterialNamePlaceholder"] = "أدخل اسم المادة الخام (مثال: لفة ورق A4)",
        ["RawMaterialNameMustBeUnique"] = "يجب أن يكون اسم المادة الخام فريداً",
        ["DimensionsAndPrice"] = "الأبعاد والسعر",
        ["EnterWidthInCm"] = "أدخل العرض بالسنتيمتر",
        ["EnterHeightInMeters"] = "أدخل الارتفاع بالأمتار",
        ["EnterTotalPrice"] = "أدخل السعر الإجمالي",
        ["Example"] = "مثال",
        ["CalculatedValuesPreview"] = "القيم المحسوبة (معاينة)",
        ["PricePerLinearMeter"] = "السعر للمتر الطولي",
        ["HowCalculationsWork"] = "كيف تعمل الحسابات",
        ["AreaFormula"] = "(العرض بالسم ÷ 100) × الارتفاع بالأمتار",
        ["PricePerM2Formula"] = "السعر الإجمالي ÷ المساحة (م²)",
        ["PricePerMFormula"] = "السعر الإجمالي ÷ الارتفاع بالأمتار",
        ["AllCalculationsAutomatic"] = "جميع الحسابات تتم تلقائياً عند الإنشاء/التحديث",

        // في _arabicTexts أضف:
        ["EditRawMaterial"] = "تعديل المادة الخام",
        ["EnterRawMaterialName"] = "أدخل اسم المادة الخام",
        ["CurrentCalculatedValues"] = "القيم المحسوبة الحالية",
        ["NewCalculatedValuesPreview"] = "القيم المحسوبة الجديدة (معاينة)",
        ["RawMaterialIsActive"] = "المادة الخام نشطة",
        ["InactiveMaterialsNotAvailable"] = "المواد غير النشطة لن تكون متاحة للاختيار",

        // في _arabicTexts أضف:
        ["RollDirectionsManagement"] = "إدارة اتجاهات اللفة",
        ["AddNewDirection"] = "إضافة اتجاه جديد",
        ["SearchDirectionsPlaceholder"] = "ابحث برقم الاتجاه أو الوصف",
        ["TotalDirections"] = "إجمالي الاتجاهات",
        ["ActiveDirections"] = "الاتجاهات النشطة",
        ["InactiveDirections"] = "الاتجاهات غير النشطة",
        ["DirectionNumber"] = "رقم الاتجاه",
        ["Direction"] = "اتجاه",
        ["NoImage"] = "لا توجد صورة",
        ["NoDescription"] = "لا يوجد وصف",
        ["DeleteDirectionConfirmation"] = "هل أنت متأكد من حذف اتجاه اللفة هذا؟",
        ["NoDirectionsFound"] = "لم يتم العثور على اتجاهات",
        ["NoDirectionsAvailable"] = "لا توجد اتجاهات لفة متاحة",
        ["StartByAddingDirection"] = "ابدأ بإضافة أول اتجاه لفة",

        // في _arabicTexts أضف:
        ["CreateRollDirection"] = "إنشاء اتجاه لفة",
        ["CreateNewRollDirection"] = "إنشاء اتجاه لفة جديد",
        ["RollDirectionInformation"] = "معلومات اتجاه اللفة",
        ["DirectionNumberPlaceholder"] = "أدخل رقم الاتجاه (مثال: 1، 2، 3)",
        ["DirectionNumberMustBeUnique"] = "يجب أن يكون رقم الاتجاه فريداً",
        ["DirectionImage"] = "صورة الاتجاه",
        ["AcceptedImageFormats"] = "الصيغ المقبولة: JPG، PNG، GIF (الحجم الأقصى: 5 ميجابايت)",
        ["ImagePreview"] = "معاينة الصورة",
        ["Preview"] = "معاينة",
        ["EnterDescriptionOptional"] = "أدخل الوصف (اختياري)",
        ["CreateDirection"] = "إنشاء الاتجاه",
        ["FileSizeTooLarge"] = "يجب أن يكون حجم الملف أقل من 5 ميجابايت",
        ["PleaseSelectImageFile"] = "الرجاء اختيار ملف صورة",

        // في _arabicTexts أضف:
        ["EditRollDirection"] = "تعديل اتجاه اللفة",
        ["EnterDirectionNumber"] = "أدخل رقم الاتجاه",
        ["CurrentImage"] = "الصورة الحالية",
        ["CurrentDirectionImage"] = "صورة الاتجاه الحالية",
        ["NoImageUploadedYet"] = "لم يتم رفع صورة بعد",
        ["ChangeImageOptional"] = "تغيير الصورة (اختياري)",
        ["LeaveEmptyToKeepCurrentImage"] = "اتركه فارغاً للاحتفاظ بالصورة الحالية. الصيغ المقبولة: JPG، PNG، GIF (الحجم الأقصى: 5 ميجابايت)",
        ["NewImagePreview"] = "معاينة الصورة الجديدة",
        ["DirectionIsActive"] = "الاتجاه نشط",

        // في _arabicTexts أضف:
        ["SystemSettings"] = "إعدادات النظام",
        ["GeneralSettings"] = "الإعدادات العامة",
        ["ApplicationSettings"] = "إعدادات التطبيق",
        ["ApplicationName"] = "اسم التطبيق",
        ["EnterApplicationName"] = "أدخل اسم التطبيق",
        ["LocalizationSettings"] = "إعدادات التوطين",
        ["Language"] = "اللغة",
        ["English"] = "الإنجليزية",
        ["Arabic"] = "العربية",
        ["Theme"] = "المظهر",
        ["Light"] = "فاتح",
        ["Dark"] = "داكن",
        ["DisplayAndPagination"] = "العرض والترقيم",
        ["ItemsPerPage"] = "العناصر في الصفحة",
        ["EnterItemsPerPage"] = "أدخل عدد العناصر في الصفحة",
        ["ItemsPerPageHint"] = "عدد العناصر المعروضة في كل صفحة (5-100)",
        ["SecurityAndSession"] = "الأمان والجلسة",
        ["SessionTimeoutMinutes"] = "مهلة الجلسة (بالدقائق)",
        ["EnterSessionTimeout"] = "أدخل مهلة الجلسة",
        ["SessionTimeoutHint"] = "المدة قبل انتهاء صلاحية الجلسة تلقائياً (5-1440 دقيقة)",
        ["DateAndTimeFormat"] = "تنسيق التاريخ والوقت",
        ["DateFormat"] = "تنسيق التاريخ",
        ["TimeFormat"] = "تنسيق الوقت",
        ["24Hour"] = "24 ساعة (HH:mm)",
        ["12Hour"] = "12 ساعة (hh:mm ص/م)",
        ["NotificationSettings"] = "إعدادات الإشعارات",
        ["EnableEmailNotifications"] = "تفعيل إشعارات البريد الإلكتروني",
        ["EmailNotificationsHint"] = "تلقي إشعارات عبر البريد الإلكتروني للأحداث المهمة",

        // في _arabicTexts أضف:
        ["SuppliersManagement"] = "إدارة الموردين",
        ["AddNewSupplier"] = "إضافة مورد جديد",
        ["SearchSuppliersPlaceholder"] = "ابحث بالكود، الاسم، الهاتف، رقم البطاقة، السجل، البريد، أو المدينة",
        ["TotalSuppliers"] = "إجمالي الموردين",
        ["ActiveSuppliers"] = "الموردين النشطين",
        ["InactiveSuppliers"] = "الموردين غير النشطين",
        ["LastCode"] = "آخر كود",
        ["Code"] = "الكود",
        ["SupplierInfo"] = "معلومات المورد",
        ["Contact"] = "الاتصال",
        ["Documents"] = "المستندات",
        ["Location"] = "الموقع",
        ["Card"] = "البطاقة",
        ["Register"] = "السجل",
        ["DeleteSupplierConfirmation"] = "هل أنت متأكد من حذف هذا المورد؟ سيتم إعادة تعيين جميع أكواد الموردين.",
        ["NoSuppliersFound"] = "لم يتم العثور على موردين",
        ["NoSuppliersAvailable"] = "لا يوجد موردين متاحين",
        ["StartByAddingSupplier"] = "ابدأ بإضافة أول مورد",

        // في _arabicTexts أضف:
        ["CreateSupplier"] = "إنشاء مورد",
        ["CreateNewSupplier"] = "إنشاء مورد جديد",
        ["SupplierInformation"] = "معلومات المورد",
        ["SupplierCodeAutoGenerated"] = "كود المورد (يُنشأ تلقائياً)",
        ["CodeWillBeAssignedAutomatically"] = "سيتم تعيين هذا الكود تلقائياً",
        ["SupplierName"] = "اسم المورد",
        ["EnterSupplierNamePlaceholder"] = "أدخل اسم المورد (مثال: شركة ABC التجارية)",
        ["SupplierNameMustBeUnique"] = "يجب أن يكون اسم المورد فريداً",
        ["CardNumber"] = "رقم البطاقة",
        ["EnterCardNumberOptional"] = "أدخل رقم البطاقة (اختياري)",
        ["CommercialRegister"] = "السجل التجاري",
        ["EnterCommercialRegisterOptional"] = "أدخل السجل التجاري (اختياري)",
        ["ContactInformation"] = "معلومات الاتصال",
        ["PhoneNumber"] = "رقم الهاتف",
        ["EnterPhoneNumberRequired"] = "أدخل رقم الهاتف (مطلوب)",
        ["Email"] = "البريد الإلكتروني",
        ["EnterEmailOptional"] = "أدخل البريد الإلكتروني (اختياري)",
        ["LocationInformation"] = "معلومات الموقع",
        ["City"] = "المدينة",
        ["EnterCityOptional"] = "أدخل المدينة (اختياري)",
        ["Country"] = "الدولة",
        ["EnterCountryOptional"] = "أدخل الدولة (اختياري)",
        ["Address"] = "العنوان",
        ["EnterFullAddressOptional"] = "أدخل العنوان الكامل (اختياري)",
        ["Notes"] = "ملاحظات",
        ["EnterNotesOptional"] = "أدخل ملاحظات أو معلومات إضافية (اختياري)",
        ["TipsForAddingSuppliers"] = "نصائح لإضافة الموردين",
        ["SupplierCodeAutoGeneratedTip"] = "يُنشأ كود المورد تلقائياً (0001، 0002، 0003...)",
        ["SupplierNameMustBeUniqueTip"] = "يجب أن يكون اسم المورد فريداً",
        ["PhoneNumberRequiredTip"] = "رقم الهاتف مطلوب لأغراض الاتصال",
        ["CardNumberOptionalTip"] = "رقم البطاقة والسجل التجاري اختياريان لكن يُنصح بهما",
        ["CodesReassignedOnDeleteTip"] = "عند حذف مورد، يتم إعادة تعيين الأكواد تلقائياً",
        ["CreateSupplier"] = "إنشاء المورد",

        // في _arabicTexts أضف:
        ["EditSupplier"] = "تعديل مورد",
        ["SupplierCodeCannotBeChanged"] = "كود المورد (لا يمكن تغييره)",
        ["CodeIsPermanentAndUnique"] = "هذا الكود دائم وفريد",
        ["EnterSupplierName"] = "أدخل اسم المورد",
        ["EnterPhoneNumber"] = "أدخل رقم الهاتف",
        ["SupplierIsActive"] = "المورد نشط",
        ["InactiveSuppliersNotAvailable"] = "الموردون غير النشطين لن يكونوا متاحين للاختيار",
        // في _arabicTexts أضف:
        ["UserManagement"] = "إدارة المستخدمين",
        ["TotalUsers"] = "إجمالي المستخدمين",
        ["UserName"] = "اسم المستخدم",
        ["Email"] = "البريد الإلكتروني",
        ["CurrentRole"] = "الدور الحالي",
        ["ChangeRole"] = "تغيير الدور",
        ["ManagePermissions"] = "إدارة الصلاحيات",
        ["Permissions"] = "الصلاحيات",
        ["NoUsersFound"] = "لم يتم العثور على مستخدمين",
        ["NoUsersFoundDescription"] = "لا يوجد مستخدمون مسجلون في النظام حالياً",

        // في _arabicTexts أضف:
        ["AssignRole"] = "تعيين دور",
        ["AssignRoleToUser"] = "تعيين دور للمستخدم",
        ["User"] = "المستخدم",
        ["ManageUserRole"] = "إدارة دور المستخدم",
        ["UserInformation"] = "معلومات المستخدم",
        ["RoleAssignment"] = "تعيين الدور",
        ["SelectNewRole"] = "اختر دور جديد",
        ["SelectRole"] = "اختر دور",
        ["SelectRoleHint"] = "اختر الدور المناسب بناءً على المسؤوليات المطلوبة",
        ["RoleDescriptions"] = "أوصاف الأدوار",
        ["AdminRoleDescription"] = "صلاحيات كاملة على جميع أجزاء النظام",
        ["ManagerRoleDescription"] = "صلاحيات إدارية مع بعض القيود",
        ["UserRoleDescription"] = "صلاحيات محدودة للاستخدام الأساسي",
        ["ImportantNote"] = "ملاحظة هامة",
        ["RoleChangeWarning"] = "تغيير دور المستخدم سيؤثر على وصوله إلى أجزاء مختلفة من النظام. تأكد من اختيار الدور المناسب.",
        ["ConfirmRoleChange"] = "هل أنت متأكد من تغيير الدور إلى {0}؟",

        // في _arabicTexts أضف:
        ["ManageUserPermissions"] = "إدارة صلاحيات المستخدم",
        ["BackToUsers"] = "العودة للمستخدمين",
        ["ManageUserPermissionsDescription"] = "إدارة الصلاحيات والأدوار",
        ["SelectPermissionsAndRoles"] = "اختيار الصلاحيات والأدوار",
        ["ChoosePermissionsDescription"] = "اختر الصلاحيات والأدوار المحددة التي يجب أن يمتلكها هذا المستخدم",
        ["SelectAll"] = "تحديد الكل",
        ["DeselectAll"] = "إلغاء تحديد الكل",
        ["TotalPermissions"] = "إجمالي الصلاحيات",
        ["SelectedPermissions"] = "الصلاحيات المحددة",
        ["TotalRoles"] = "إجمالي الأدوار",
        ["NoRolesDefinedForPermission"] = "لم يتم تعريف أدوار لهذه الصلاحية",
        ["NoPermissionsAvailable"] = "لا توجد صلاحيات متاحة",
        ["PleaseCreatePermissionsFirst"] = "يرجى إنشاء الصلاحيات أولاً من قسم إدارة الصلاحيات",
        ["SavePermissions"] = "حفظ الصلاحيات",

        // Print Orders
        ["PrintOrdersManagement"] = "إدارة طلبات الطباعة",
        ["AddNewPrintOrder"] = "إضافة طلب طباعة جديد",
        ["SearchPrintOrdersPlaceholder"] = "ابحث برقم الطلب، المورد، أو المنتج",
        ["AllStatuses"] = "جميع الحالات",
        ["AllStages"] = "جميع المراحل",
        ["FilterActive"] = "الفلتر نشط",
        ["TotalOrders"] = "إجمالي الطلبات",
        ["PendingOrders"] = "الطلبات المعلقة",
        ["CompletedOrders"] = "الطلبات المكتملة",
        ["InProgressOrders"] = "الطلبات قيد التنفيذ",
        ["OrderNumber"] = "رقم الطلب",
        ["OrderDate"] = "تاريخ الطلب",
        ["ExpectedDeliveryDate"] = "تاريخ التسليم المتوقع",
        ["ActualDeliveryDate"] = "تاريخ التسليم الفعلي",
        ["Quantity"] = "الكمية",
        ["EnterQuantity"] = "أدخل الكمية",
        ["EnterOrderNumber"] = "أدخل رقم الطلب",
        ["OrderStatusBreakdown"] = "تفاصيل حالة الطلبات",
        ["OrderStageBreakdown"] = "تفاصيل مراحل الطلبات",
        ["SupplierAndProduct"] = "المورد والمنتج",
        ["StatusAndStage"] = "الحالة والمرحلة",
        ["Stage"] = "المرحلة",
        ["SelectRollDirection"] = "اختر اتجاه اللفة",
        ["Dates"] = "التواريخ",
        ["PrintOrderDetails"] = "تفاصيل طلب الطباعة",
        ["SupplierInformation"] = "معلومات المورد",
        ["CreatePrintOrder"] = "إنشاء طلب طباعة",
        ["EditPrintOrder"] = "تعديل طلب الطباعة",
        ["DeletePrintOrder"] = "حذف طلب الطباعة",
        ["DeletePrintOrderConfirmation"] = "هل أنت متأكد من حذف طلب الطباعة هذا؟",
        ["ConfirmDeletePrintOrder"] = "هل أنت متأكد من رغبتك في حذف هذا الطلب؟ هذا الإجراء لا يمكن التراجع عنه.",
        ["PrintOrderIsActive"] = "طلب الطباعة نشط",
        ["InactivePrintOrdersNotAvailable"] = "طلبات الطباعة غير النشطة لن تكون متاحة",
        ["NoPrintOrdersFound"] = "لم يتم العثور على طلبات طباعة",
        ["NoPrintOrdersAvailable"] = "لا توجد طلبات طباعة متاحة",
        ["StartByAddingPrintOrder"] = "ابدأ بإضافة أول طلب طباعة",
        ["TipsForAddingPrintOrders"] = "نصائح لإضافة طلبات الطباعة",
        ["OrderNumberMustBeUnique"] = "يجب أن يكون رقم الطلب فريداً",
        ["ExpectedDeliveryDateMustBeAfterOrderDate"] = "يجب أن يكون تاريخ التسليم المتوقع بعد تاريخ الطلب",
        ["SelectAppropriateStatusAndStage"] = "اختر الحالة والمرحلة المناسبة للطلب",
        ["RollDirectionIsOptional"] = "اتجاه اللفة اختياري ويمكن تركه فارغاً",
        ["PrintOrderStatistics"] = "إحصائيات طلبات الطباعة",
        ["AllPrintOrders"] = "جميع طلبات الطباعة",
        ["OfTotal"] = "من الإجمالي",
        ["NoOrders"] = "لا توجد طلبات",
        ["QuickActions"] = "إجراءات سريعة",
        ["ViewAllOrders"] = "عرض جميع الطلبات",
        ["CreateNewOrder"] = "إنشاء طلب جديد",
        ["ViewPendingOrders"] = "عرض الطلبات المعلقة",
        ["ViewCompletedOrders"] = "عرض الطلبات المكتملة",
        ["Details"] = "التفاصيل",

        // Order Status Enum
        ["Pending"] = "معلق",
        ["Ready"] = "جاهز",
        ["NotPrinted"] = "غير مطبوع",
        ["Cancelled"] = "ملغي",

        // Order Stage Enum
        ["Order"] = "طلب",
        ["Review"] = "مراجعة",
        ["Manufacturing"] = "تصنيع",
        ["Printing"] = "طباعة",
    };

    // English Translations
    private readonly Dictionary<string, string> _englishTexts = new()
    {
        // في _englishTexts أضف:
        ["ManageUserPermissions"] = "Manage User Permissions",
        ["BackToUsers"] = "Back to Users",
        ["ManageUserPermissionsDescription"] = "Manage Permissions and Roles",
        ["SelectPermissionsAndRoles"] = "Select Permissions and Roles",
        ["ChoosePermissionsDescription"] = "Choose which permissions and specific roles this user should have",
        ["SelectAll"] = "Select All",
        ["DeselectAll"] = "Deselect All",
        ["TotalPermissions"] = "Total Permissions",
        ["SelectedPermissions"] = "Selected Permissions",
        ["TotalRoles"] = "Total Roles",
        ["NoRolesDefinedForPermission"] = "No roles defined for this permission",
        ["NoPermissionsAvailable"] = "No permissions available",
        ["PleaseCreatePermissionsFirst"] = "Please create permissions first from the Permissions Management section",
        ["SavePermissions"] = "Save Permissions",
        // في _englishTexts أضف:
        ["AssignRole"] = "Assign Role",
        ["AssignRoleToUser"] = "Assign Role to User",
        ["User"] = "User",
        ["ManageUserRole"] = "Manage User Role",
        ["UserInformation"] = "User Information",
        ["RoleAssignment"] = "Role Assignment",
        ["SelectNewRole"] = "Select New Role",
        ["SelectRole"] = "Select Role",
        ["SelectRoleHint"] = "Choose the appropriate role based on required responsibilities",
        ["RoleDescriptions"] = "Role Descriptions",
        ["AdminRoleDescription"] = "Full access to all parts of the system",
        ["ManagerRoleDescription"] = "Administrative permissions with some restrictions",
        ["UserRoleDescription"] = "Limited permissions for basic usage",
        ["ImportantNote"] = "Important Note",
        ["RoleChangeWarning"] = "Changing user role will affect their access to different parts of the system. Make sure to choose the appropriate role.",
        ["ConfirmRoleChange"] = "Are you sure you want to change the role to {0}?",
        // في _englishTexts أضف:
        ["UserManagement"] = "User Management",
        ["TotalUsers"] = "Total Users",
        ["UserName"] = "User Name",
        ["Email"] = "Email",
        ["CurrentRole"] = "Current Role",
        ["ChangeRole"] = "Change Role",
        ["ManagePermissions"] = "Manage Permissions",
        ["Permissions"] = "Permissions",
        ["NoUsersFound"] = "No Users Found",
        ["NoUsersFoundDescription"] = "There are no registered users in the system at this time",
        // في _englishTexts أضف:
        ["EditSupplier"] = "Edit Supplier",
        ["SupplierCodeCannotBeChanged"] = "Supplier Code (Cannot be changed)",
        ["CodeIsPermanentAndUnique"] = "This code is permanent and unique",
        ["EnterSupplierName"] = "Enter supplier name",
        ["EnterPhoneNumber"] = "Enter phone number",
        ["SupplierIsActive"] = "Supplier is Active",
        ["InactiveSuppliersNotAvailable"] = "Inactive suppliers will not be available for selection",
        // في _englishTexts أضف:
        ["CreateSupplier"] = "Create Supplier",
        ["CreateNewSupplier"] = "Create New Supplier",
        ["SupplierInformation"] = "Supplier Information",
        ["SupplierCodeAutoGenerated"] = "Supplier Code (Auto-Generated)",
        ["CodeWillBeAssignedAutomatically"] = "This code will be assigned automatically",
        ["SupplierName"] = "Supplier Name",
        ["EnterSupplierNamePlaceholder"] = "Enter supplier name (e.g., ABC Trading Company)",
        ["SupplierNameMustBeUnique"] = "Supplier name must be unique",
        ["CardNumber"] = "Card Number",
        ["EnterCardNumberOptional"] = "Enter card number (optional)",
        ["CommercialRegister"] = "Commercial Register",
        ["EnterCommercialRegisterOptional"] = "Enter commercial register (optional)",
        ["ContactInformation"] = "Contact Information",
        ["PhoneNumber"] = "Phone Number",
        ["EnterPhoneNumberRequired"] = "Enter phone number (required)",
        ["Email"] = "Email",
        ["EnterEmailOptional"] = "Enter email (optional)",
        ["LocationInformation"] = "Location Information",
        ["City"] = "City",
        ["EnterCityOptional"] = "Enter city (optional)",
        ["Country"] = "Country",
        ["EnterCountryOptional"] = "Enter country (optional)",
        ["Address"] = "Address",
        ["EnterFullAddressOptional"] = "Enter full address (optional)",
        ["Notes"] = "Notes",
        ["EnterNotesOptional"] = "Enter notes or additional information (optional)",
        ["TipsForAddingSuppliers"] = "Tips for Adding Suppliers",
        ["SupplierCodeAutoGeneratedTip"] = "Supplier code is generated automatically (0001, 0002, 0003...)",
        ["SupplierNameMustBeUniqueTip"] = "Supplier name must be unique",
        ["PhoneNumberRequiredTip"] = "Phone number is required for contact purposes",
        ["CardNumberOptionalTip"] = "Card number and commercial register are optional but recommended",
        ["CodesReassignedOnDeleteTip"] = "When a supplier is deleted, codes are automatically reassigned",
        // في _englishTexts أضف:
        ["SuppliersManagement"] = "Suppliers Management",
        ["AddNewSupplier"] = "Add New Supplier",
        ["SearchSuppliersPlaceholder"] = "Search by code, name, phone, card number, register, email, or city",
        ["TotalSuppliers"] = "Total Suppliers",
        ["ActiveSuppliers"] = "Active Suppliers",
        ["InactiveSuppliers"] = "Inactive Suppliers",
        ["LastCode"] = "Last Code",
        ["Code"] = "Code",
        ["SupplierInfo"] = "Supplier Info",
        ["Contact"] = "Contact",
        ["Documents"] = "Documents",
        ["Location"] = "Location",
        ["Card"] = "Card",
        ["Register"] = "Register",
        ["DeleteSupplierConfirmation"] = "Are you sure you want to delete this supplier? All supplier codes will be reassigned.",
        ["NoSuppliersFound"] = "No Suppliers Found",
        ["NoSuppliersAvailable"] = "No Suppliers Available",
        ["StartByAddingSupplier"] = "Start by adding your first supplier",
        // في _englishTexts أضف:
        ["SystemSettings"] = "System Settings",
        ["GeneralSettings"] = "General Settings",
        ["ApplicationSettings"] = "Application Settings",
        ["ApplicationName"] = "Application Name",
        ["EnterApplicationName"] = "Enter application name",
        ["LocalizationSettings"] = "Localization Settings",
        ["Language"] = "Language",
        ["English"] = "English",
        ["Arabic"] = "Arabic",
        ["Theme"] = "Theme",
        ["Light"] = "Light",
        ["Dark"] = "Dark",
        ["DisplayAndPagination"] = "Display & Pagination",
        ["ItemsPerPage"] = "Items Per Page",
        ["EnterItemsPerPage"] = "Enter items per page",
        ["ItemsPerPageHint"] = "Number of items displayed per page (5-100)",
        ["SecurityAndSession"] = "Security & Session",
        ["SessionTimeoutMinutes"] = "Session Timeout (minutes)",
        ["EnterSessionTimeout"] = "Enter session timeout",
        ["SessionTimeoutHint"] = "Time before session expires automatically (5-1440 minutes)",
        ["DateAndTimeFormat"] = "Date & Time Format",
        ["DateFormat"] = "Date Format",
        ["TimeFormat"] = "Time Format",
        ["24Hour"] = "24 Hour (HH:mm)",
        ["12Hour"] = "12 Hour (hh:mm AM/PM)",
        ["NotificationSettings"] = "Notification Settings",
        ["EnableEmailNotifications"] = "Enable Email Notifications",
        ["EmailNotificationsHint"] = "Receive email notifications for important events",
        // في _englishTexts أضف:
        ["EditRollDirection"] = "Edit Roll Direction",
        ["EnterDirectionNumber"] = "Enter direction number",
        ["CurrentImage"] = "Current Image",
        ["CurrentDirectionImage"] = "Current Direction Image",
        ["NoImageUploadedYet"] = "No image uploaded yet",
        ["ChangeImageOptional"] = "Change Image (Optional)",
        ["LeaveEmptyToKeepCurrentImage"] = "Leave empty to keep current image. Accepted formats: JPG, PNG, GIF (Max size: 5MB)",
        ["NewImagePreview"] = "New Image Preview",
        ["DirectionIsActive"] = "Direction is Active",
        // في _englishTexts أضف:
        ["CreateRollDirection"] = "Create Roll Direction",
        ["CreateNewRollDirection"] = "Create New Roll Direction",
        ["RollDirectionInformation"] = "Roll Direction Information",
        ["DirectionNumberPlaceholder"] = "Enter direction number (e.g., 1, 2, 3)",
        ["DirectionNumberMustBeUnique"] = "Direction number must be unique",
        ["DirectionImage"] = "Direction Image",
        ["AcceptedImageFormats"] = "Accepted formats: JPG, PNG, GIF (Max size: 5MB)",
        ["ImagePreview"] = "Image Preview",
        ["Preview"] = "Preview",
        ["EnterDescriptionOptional"] = "Enter description (optional)",
        ["CreateDirection"] = "Create Direction",
        ["FileSizeTooLarge"] = "File size must be less than 5MB",
        ["PleaseSelectImageFile"] = "Please select an image file",
        // في _englishTexts أضف:
        ["RollDirectionsManagement"] = "Roll Directions Management",
        ["AddNewDirection"] = "Add New Direction",
        ["SearchDirectionsPlaceholder"] = "Search by direction number or description",
        ["TotalDirections"] = "Total Directions",
        ["ActiveDirections"] = "Active Directions",
        ["InactiveDirections"] = "Inactive Directions",
        ["DirectionNumber"] = "Direction #",
        ["Direction"] = "Direction",
        ["NoImage"] = "No Image",
        ["NoDescription"] = "No description",
        ["DeleteDirectionConfirmation"] = "Are you sure you want to delete this roll direction?",
        ["NoDirectionsFound"] = "No Directions Found",
        ["NoDirectionsAvailable"] = "No Roll Directions Available",
        ["StartByAddingDirection"] = "Start by adding your first roll direction",
        // في _englishTexts أضف:
        ["EditRawMaterial"] = "Edit Raw Material",
        ["EnterRawMaterialName"] = "Enter raw material name",
        ["CurrentCalculatedValues"] = "Current Calculated Values",
        ["NewCalculatedValuesPreview"] = "New Calculated Values (Preview)",
        ["RawMaterialIsActive"] = "Raw Material is Active",
        ["InactiveMaterialsNotAvailable"] = "Inactive materials will not be available for selection",
        // في _englishTexts أضف:
        ["CreateRawMaterial"] = "Create Raw Material",
        ["CreateNewRawMaterial"] = "Create New Raw Material",
        ["RawMaterialInformation"] = "Raw Material Information",
        ["RawMaterialName"] = "Raw Material Name",
        ["RawMaterialNamePlaceholder"] = "Enter raw material name (e.g., Paper Roll A4)",
        ["RawMaterialNameMustBeUnique"] = "Raw material name must be unique",
        ["DimensionsAndPrice"] = "Dimensions & Price",
        ["EnterWidthInCm"] = "Enter width in cm",
        ["EnterHeightInMeters"] = "Enter height in meters",
        ["EnterTotalPrice"] = "Enter total price",
        ["Example"] = "Example",
        ["CalculatedValuesPreview"] = "Calculated Values (Preview)",
        ["PricePerLinearMeter"] = "Price per Linear Meter",
        ["HowCalculationsWork"] = "How Calculations Work",
        ["AreaFormula"] = "(Width in cm ÷ 100) × Height in meters",
        ["PricePerM2Formula"] = "Total Price ÷ Area (m²)",
        ["PricePerMFormula"] = "Total Price ÷ Height in meters",
        ["AllCalculationsAutomatic"] = "All calculations are done automatically when you create/update",
        // في _englishTexts أضف:
        ["RawMaterialsManagement"] = "Raw Materials Management",
        ["AddNewRawMaterial"] = "Add New Raw Material",
        ["SearchRawMaterialsPlaceholder"] = "Search by name, width, height, or price",
        ["TotalMaterials"] = "Total Materials",
        ["ActiveMaterials"] = "Active Materials",
        ["InactiveMaterials"] = "Inactive Materials",
        ["MaterialName"] = "Material Name",
        ["WidthCm"] = "Width (cm)",
        ["HeightM"] = "Height (m)",
        ["AreaM2"] = "Area (m²)",
        ["PricePerM2"] = "Price/m²",
        ["PricePerM"] = "Price/m",
        ["Cm"] = "cm",
        ["M"] = "m",
        ["M2"] = "m²",
        ["DeleteRawMaterialConfirmation"] = "Are you sure you want to delete this raw material?",
        ["NoRawMaterialsFound"] = "No Raw Materials Found",
        ["NoRawMaterialsAvailable"] = "No Raw Materials Available",
        ["StartByAddingRawMaterial"] = "Start by adding your first raw material",
        // في _englishTexts أضف:
        ["EditProduct"] = "Edit Product",
        ["EnterProductName"] = "Enter product name",
        ["ProductCodeCannotBeChanged"] = "Product code cannot be changed after creation",
        ["ProductIsActive"] = "Product is Active",
        ["InactiveProductsNotAvailable"] = "Inactive products will not be available for selection in orders",
        ["At"] = "at",
        // في _englishTexts أضف:
        ["CreateProduct"] = "Create Product",
        ["CreateNewProduct"] = "Create New Product",
        ["ProductInformation"] = "Product Information",
        ["BasicInformation"] = "Basic Information",
        ["ProductNamePlaceholder"] = "Enter product name (e.g., Gift Box Premium)",
        ["SelectSupplier"] = "Select Supplier",
        ["WillBeAutoGenerated"] = "Will be auto-generated",
        ["GenerateCode"] = "Generate Code",
        ["ProductCodeFormat"] = "Format: Supplier Code + 01, 02, 03...",
        ["ProductTypeAndMaterial"] = "Product Type & Material",
        ["ProductType"] = "Product Type",
        ["SelectRawMaterial"] = "Select Raw Material",
        ["SelectManufacturingAdditionsHint"] = "Select all manufacturing additions that apply to this product",
        ["NoManufacturingAdditionsAvailable"] = "No manufacturing additions available. Please add additions first.",
        ["AddManufacturingAddition"] = "Add Manufacturing Addition",
        ["DescriptionOptional"] = "Description (Optional)",
        ["ProductDescriptionPlaceholder"] = "Enter product description, notes, or specifications...",
        ["ExampleProductCodeGeneration"] = "Example Product Code Generation",
        ["ProductCodeExample1"] = "If supplier code is SUP, product codes will be: SUP01, SUP02, SUP03...",
        ["ProductCodeExample2"] = "If supplier code is ABC, product codes will be: ABC01, ABC02, ABC03...",
        ["ProductCodeExample3"] = "The system automatically generates the next available number",
        ["ProductCodeExample4"] = "Product codes are unique and cannot be duplicated",
        ["PleaseSelectSupplierFirst"] = "Please select a supplier first",
        ["Generating"] = "Generating",
        ["CodeGenerated"] = "Code Generated",
        ["ErrorGeneratingProductCode"] = "Error generating product code",
        // في _englishTexts أضف:
        ["ProductsManagement"] = "Products Management",
        ["AddNewProduct"] = "Add New Product",
        ["SearchProductsPlaceholder"] = "Search by product name, code, supplier, or raw material",
        ["TotalProducts"] = "Total Products",
        ["ActiveProducts"] = "Active Products",
        ["PrintedProducts"] = "Printed Products",
        ["NonPrintedProducts"] = "Non-Printed Products",
        ["ProductCode"] = "Product Code",
        ["ProductName"] = "Product Name",
        ["Type"] = "Type",
        ["Supplier"] = "Supplier",
        ["RawMaterial"] = "Raw Material",
        ["Additions"] = "Additions",
        ["Printed"] = "Printed",
        ["NonPrinted"] = "Non-Printed",
        ["None"] = "None",
        ["DeleteProductConfirmation"] = "Are you sure you want to delete this product?",
        ["NoProductsFound"] = "No Products Found",
        ["NoProductsAvailable"] = "No Products Available",
        ["StartByAddingProduct"] = "Start by adding your first product",
        // في _englishTexts أضف:
        ["EditPermission"] = "Edit Permission",
        ["UpdatePermissionDetails"] = "Update Permission Details",
        ["Warning"] = "Warning",
        ["ChangePermissionCodeWarning"] = "Changing the permission code may affect systems and roles using this permission. Make sure to update all related references.",
        // في _englishTexts أضف:
        ["PermissionDetails"] = "Permission Details",
        ["PermissionNamePlaceholder"] = "e.g., View Users, Edit Posts",
        ["PermissionCode"] = "Permission Code",
        ["PermissionCodePlaceholder"] = "e.g., VIEW_USERS, EDIT_POSTS",
        ["PermissionCodeHint"] = "Use uppercase letters and underscores only (e.g., MANAGE_USERS)",
        ["PermissionDescriptionPlaceholder"] = "Describe what this permission allows users to do...",
        ["PermissionNameShouldBeClear"] = "Permission name should be clear and descriptive",
        ["PermissionCodeMustBeUnique"] = "Permission code must be unique in the system",
        ["UseUppercaseForCode"] = "Use uppercase letters and underscores for the code",
        ["DescriptionHelpsUnderstandPermission"] = "Description helps understand the purpose of the permission",
        // في _englishTexts أضف:
        ["Permissions"] = "Permissions",
        ["PermissionsManagement"] = "Permissions Management",
        ["CreateNewPermission"] = "Create New Permission",
        ["PermissionName"] = "Permission Name",
        ["Code"] = "Code",
        ["ManageRoles"] = "Manage Roles",
        ["Roles"] = "Roles",
        ["DeletePermissionConfirmation"] = "Are you sure you want to delete this permission?",
        ["NoPermissionsFound"] = "No Permissions Found",
        ["CreateFirstPermissionToGetStarted"] = "Create your first permission to get started",
        ["CreatePermission"] = "Create Permission",
        // في _englishTexts أضف:
        ["MoldsCount"] = "Molds Count",
        ["NoDescription"] = "No Description",
        ["DeleteMoldShapeConfirmation"] = "Are you sure you want to delete this mold shape?",
        ["CannotDeleteHasMolds"] = "Cannot delete - has",
        // في _englishTexts أضف:
        ["EditMoldShape"] = "Edit Mold Shape",
        ["CurrentImage"] = "Current Image",
        ["UploadImage"] = "Upload Image",
        ["ChangeImage"] = "Change Image",
        ["LeaveEmptyToKeepCurrentImage"] = "Leave empty to keep current image. Allowed formats: JPG, JPEG, PNG, GIF, BMP (Max size: 5MB)",
        ["NewImagePreview"] = "New Image Preview",
        ["MoldShapeIsActive"] = "Mold Shape is Active",
        ["InactiveMoldShapesNotAvailable"] = "Inactive mold shapes will not be available for selection",
        ["ThisMoldShapeUsedIn"] = "This mold shape is used in",
        // في _englishTexts أضف:
        ["CreateMoldShape"] = "Create Mold Shape",
        ["MoldShapeInformation"] = "Mold Shape Information",
        ["MoldShapeName"] = "Mold Shape Name",
        ["EnterMoldShapeName"] = "Enter mold shape name",
        ["ShapeImage"] = "Shape Image",
        ["ImageFormatInfo"] = "Allowed formats: JPG, JPEG, PNG, GIF, BMP (Max size: 5MB)",
        ["ImagePreview"] = "Image Preview",
        ["MoldShapeNameMustBeUnique"] = "Mold shape name must be unique",
        ["ShapeImageHelpsIdentification"] = "Shape image helps identify the shape easily",
        ["DescriptionIsOptionalButRecommended"] = "Description is optional but recommended",

        // في _englishTexts أضف:
        ["MoldShapes"] = "Mold Shapes",
        ["MoldShapeManagement"] = "Mold Shape Management",
        ["SearchMoldShapesPlaceholder"] = "Search by shape name",
        ["TotalMoldShapes"] = "Total Shapes",
        ["ActiveMoldShapes"] = "Active Shapes",
        ["NoMoldShapesAvailable"] = "No Mold Shapes Available",
        ["StartByAddingMoldShape"] = "Start by adding your first mold shape",
        // في _englishTexts أضف:
        ["PrintedSize"] = "Printed Size",
        ["PlainSize"] = "Plain Size",
        ["DeleteMoldConfirmation"] = "Are you sure you want to delete this mold?",
        // في _englishTexts أضف:
        ["EditMold"] = "Edit Mold",
        ["MoldIsActive"] = "Mold is Active",
        ["InactiveMoldsNotAvailable"] = "Inactive molds will not be available for selection",
        // في _englishTexts أضف:
        ["CreateMold"] = "Create Mold",
        ["MoldInformation"] = "Mold Information",
        ["MoldNumber"] = "Mold Number",
        ["EnterMoldNumber"] = "Enter mold number",
        ["MoldShape"] = "Mold Shape",
        ["SelectMoldShape"] = "Select Mold Shape",
        ["EnterWidth"] = "Enter width",
        ["EnterHeight"] = "Enter height",
        ["AutoCalculated"] = "Auto Calculated",
        ["PrintedRawMaterialSize"] = "Printed Raw Material Size",
        ["PlainRawMaterialSize"] = "Plain Raw Material Size",
        ["EnterDescription"] = "Enter description",
        ["CalculationFormula"] = "Calculation Formula",
        ["TotalEyesFormula"] = "Total Eyes = Width × Height (automatically calculated when values are entered)",
        // في _englishTexts أضف:
        ["Molds"] = "Molds",
        ["MoldManagement"] = "Mold Management",
        ["SearchMoldsPlaceholder"] = "Search by name or description",
        ["TotalMolds"] = "Total Molds",
        ["ActiveMolds"] = "Active Molds",
        ["TotalEyes"] = "Total Eyes",
        ["NoMoldsAvailable"] = "No Molds Available",
        ["StartByAddingMold"] = "Start by adding your first mold",
        // في _englishTexts أضف:
        ["EditManufacturingAddition"] = "Edit Manufacturing Addition",
        ["AdditionIsActive"] = "Addition is Active",
        ["InactiveAdditionsNotAvailableForOrders"] = "Inactive additions will not be available for selection in orders",
        ["CommonManufacturingAdditions"] = "Common Manufacturing Additions",
        // في _englishTexts أضف:
        ["CreateManufacturingAddition"] = "Create Manufacturing Addition",
        ["CreateNewManufacturingAddition"] = "Create New Manufacturing Addition",
        ["ManufacturingAdditionInformation"] = "Manufacturing Addition Information",
        ["BasicInformation"] = "Basic Information",
        ["EnterAdditionName"] = "Enter addition name (e.g., Lamination, UV Coating, Die Cutting)",
        ["AdditionNameMustBeUnique"] = "Addition name must be unique",
        ["ExamplesOfManufacturingAdditions"] = "Examples of Manufacturing Additions",
        ["AdditionExample1"] = "Cliché (كليشة)",
        ["AdditionExample2"] = "Labor Work (شغيلة)",
        ["ImportantNotes"] = "Important Notes",
        ["UseClearDescriptiveNames"] = "Use clear and descriptive names for additions",
        ["AdditionsEnhanceProductQuality"] = "Additions can be used to enhance product quality",
        ["CanActivateDeactivateAnytime"] = "You can activate/deactivate additions at any time",
        ["InactiveAdditionsNotAvailable"] = "Inactive additions won't be available for selection",
        ["CreateAddition"] = "Create Addition",
        // في _englishTexts أضف:
        ["ManufacturingAdditionsManagement"] = "Manufacturing Additions Management",
        ["AddNewAddition"] = "Add New Addition",
        ["SearchAdditionsPlaceholder"] = "Search by addition name...",
        ["TotalAdditions"] = "Total Additions",
        ["ActiveAdditions"] = "Active Additions",
        ["InactiveAdditions"] = "Inactive Additions",
        ["AdditionName"] = "Addition Name",
        ["DeleteAdditionConfirmation"] = "Are you sure you want to delete this addition?",
        ["NoAdditionsAvailable"] = "No Manufacturing Additions Available",
        ["StartByAddingAddition"] = "Start by adding your first manufacturing addition",
        // في _englishTexts أضف:
        ["EditMachine"] = "Edit Machine",
        ["MachineIsActive"] = "Machine is Active",
        ["InactiveMachinesNotAvailable"] = "Inactive machines will not be available for selection in printing operations",
        // في _englishTexts أضف:
        ["CreateMachine"] = "Create Machine",
        ["CreateNewMachine"] = "Create New Machine",
        ["MachineInformation"] = "Machine Information",
        ["EnterMachineName"] = "Enter machine name (e.g., HP Indigo 7600)",
        ["MaxWidth"] = "Max Width",
        ["EnterMaximumWidth"] = "Enter maximum width",
        ["MaxWidthHelp"] = "Maximum printing width for this machine in millimeters",
        ["ModelNumberPlaceholder"] = "e.g., XR-2000",
        ["ManufacturerPlaceholder"] = "e.g., HP, Canon, Epson",
        ["MachineDescriptionPlaceholder"] = "Enter machine description, specifications, or notes (optional)",
        ["TipsForAddingMachines"] = "Tips for Adding Machines",
        ["UseDescriptiveMachineNames"] = "Use descriptive names that identify the machine easily",
        ["EnsureMaxWidthAccurate"] = "Ensure maximum width is accurate for proper calculations",
        ["IncludeModelNumberForReference"] = "Include model number for future reference",
        ["AddSpecialNotesInDescription"] = "Add any special notes about the machine in the description",

        // في _englishTexts أضف:
        ["MachinesManagement"] = "Machines Management",
        ["AddNewMachine"] = "Add New Machine",
        ["SearchMachinesPlaceholder"] = "Search by name, model, manufacturer, or max width...",
        ["TotalMachines"] = "Total Machines",
        ["ActiveMachines"] = "Active Machines",
        ["InactiveMachines"] = "Inactive Machines",
        ["MaxWidthMm"] = "Max Width (mm)",
        ["MachineName"] = "Machine Name",
        ["ModelNumber"] = "Model Number",
        ["Manufacturer"] = "Manufacturer",
        ["DeleteMachineConfirmation"] = "Are you sure you want to delete this machine?",
        ["NoMachinesAvailable"] = "No Machines Available",
        ["StartByAddingMachine"] = "Start by adding your first machine",
        // في _englishTexts أضف:
        ["KnivesManagement"] = "Knives Management",
        ["AddNewKnife"] = "Add New Knife",
        ["SearchKnivesPlaceholder"] = "Search by knife name, factor, or description...",
        ["TotalKnives"] = "Total Knives",
        ["ActiveKnives"] = "Active Knives",
        ["InactiveKnives"] = "Inactive Knives",
        ["AverageFactor"] = "Average Factor",
        ["DeleteKnifeConfirmation"] = "Are you sure you want to delete this knife?",
        ["NoKnivesAvailable"] = "No Knives Available",
        ["StartByAddingKnife"] = "Start by adding your first knife",
        // في _englishTexts أضف:
        ["EditKnife"] = "Edit Knife",
        ["KnifeIsActive"] = "Knife is Active",
        // في _englishTexts أضف:
        ["CreateKnife"] = "Create Knife",
        ["CreateNewKnife"] = "Create New Knife",
        ["KnifeInformation"] = "Knife Information",
        ["KnifeName"] = "Knife Name",
        ["EnterKnifeName"] = "Enter knife name (e.g., Standard Blade 10mm)",
        ["KnifeNameMustBeUnique"] = "Knife name must be unique",
        ["KnifeFactor"] = "Knife Factor",
        ["EnterKnifeFactor"] = "Enter knife factor (e.g., 1.15)",
        ["KnifeFactorDescription"] = "The multiplication factor for this knife type",
        ["TipsForAddingKnives"] = "Tips for Adding Knives",
        ["UseDescriptiveNamesWithBladeSize"] = "Use descriptive names including blade size if applicable",
        ["KnifeFactorUsedInCuttingCalculations"] = "Knife factor is used in cutting calculations",
        ["CommonKnifeFactorsRange"] = "Common factors range from 0.8 to 2.0",
        ["HigherFactorMeansThickerBlades"] = "Higher factor means thicker/sharper blades",
        // في _englishTexts أضف:
        ["Coefficient"] = "Coefficient",
        ["Width"] = "Width",
        ["Height"] = "Height",
        ["DeleteCoreConfirmation"] = "Are you sure you want to delete this core?",
        // في _englishTexts أضف:
        ["EditCore"] = "Edit Core",
        ["CoreCoefficientUsedForCalculations"] = "Core coefficient is used for calculations",
        ["CoreIsActive"] = "Core is Active",
        // في _englishTexts أضف:
        ["CreateCore"] = "Create Core",
        ["CreateNewCore"] = "Create New Core",
        ["CoreInformation"] = "Core Information",
        ["EnterCoreName"] = "Enter core name (e.g., Small Core, Large Core)",
        ["EnterCoefficientValue"] = "Enter coefficient value",
        ["CoreCoefficientHelp"] = "Core coefficient is used for calculations (e.g., 0.5, 1.25, 2.0)",
        ["WidthInMm"] = "Width in mm",
        ["HeightInMm"] = "Height in mm",

        // في _englishTexts أضف:
        ["SearchCoresPlaceholder"] = "Search by name, coefficient, width, or height...",
        ["TotalCores"] = "Total Cores",
        ["ActiveCores"] = "Active Cores",
        ["InactiveCores"] = "Inactive Cores",
        ["NoCoresAvailable"] = "No Cores Available",
        ["StartByAddingCore"] = "Start by adding your first core",
        // في _englishTexts أضف:
        ["EditCarton"] = "Edit Carton",
        ["CartonIsActive"] = "Carton is Active",
        ["Created"] = "Created",
        // في _englishTexts:
        ["LoginSuccessful"] = "Login Successful",
        ["InvalidLoginAttempt"] = "Invalid Login Attempt",
        ["RegistrationSuccessful"] = "Registration Successful",
        ["LogoutSuccessful"] = "Logout Successful",
        // في _englishTexts أضف:
        ["WelcomeBack"] = "Welcome back! Please login to your account",
        ["Email"] = "Email Address",
        ["EnterEmail"] = "Enter your email",
        ["Password"] = "Password",
        ["EnterPassword"] = "Enter your password",
        ["RememberMe"] = "Remember me",
        ["DontHaveAccount"] = "Don't have an account?",
        ["RegisterHere"] = "Register here",
        ["CreateNewAccount"] = "Create a new account",
        ["FullName"] = "Full Name",
        ["EnterFullName"] = "Enter your full name",
        ["ConfirmPassword"] = "Confirm Password",
        ["ReenterPassword"] = "Re-enter your password",
        ["AlreadyHaveAccount"] = "Already have an account?",
        ["LoginHere"] = "Login here",
        // في _englishTexts أضف:
        ["Users"] = "Users",
        ["Permissions"] = "Permissions",
        ["Welcome"] = "Welcome",
        ["Logout"] = "Logout",
        ["Register"] = "Register",
        ["AllRightsReserved"] = "All Rights Reserved",
        ["Materials"] = "Materials",
        ["Production"] = "Production",
        ["RollDirections"] = "Roll Directions",
        // Navigation
        ["Home"] = "Home",
        ["Dashboard"] = "Dashboard",
        ["Machines"] = "Machines",
        ["MoldShapes"] = "Mold Shapes",
        ["Molds"] = "Molds",
        ["Cores"] = "Cores",
        ["Settings"] = "Settings",

        // Common
        ["Search"] = "Search",
        ["SearchPlaceholder"] = "Search by name or description",
        ["Reset"] = "Reset",
        ["AddNew"] = "Add New",
        ["Create"] = "Create",
        ["Edit"] = "Edit",
        ["Delete"] = "Delete",
        ["Cancel"] = "Cancel",
        ["Save"] = "Save",
        ["SaveChanges"] = "Save Changes",
        ["BackToList"] = "Back to List",
        ["Actions"] = "Actions",
        ["Status"] = "Status",
        ["Active"] = "Active",
        ["Inactive"] = "Inactive",
        ["IsActive"] = "Is Active",
        ["Activate"] = "Activate",
        ["Deactivate"] = "Deactivate",
        ["Description"] = "Description",
        ["CreatedDate"] = "Created Date",
        ["LastModified"] = "Last Modified",
        ["NoResultsFound"] = "No Results Found",
        ["NoDataAvailable"] = "No Data Available",
        ["DeleteConfirmation"] = "Are you sure you want to delete this record?",
        ["TotalRecords"] = "Total Records",
        ["ActiveRecords"] = "Active Records",
        ["Optional"] = "Optional",
        ["AutoCalculated"] = "Auto Calculated",
        ["Statistics"] = "Statistics",
        ["ImagePreview"] = "Image Preview",
        ["CurrentImage"] = "Current Image",
        ["UploadImage"] = "Upload Image",
        ["ChangeImage"] = "Change Image",

        // Machines
        ["Machine"] = "Machine",
        ["MachineManagement"] = "Machine Management",
        ["MachineName"] = "Machine Name",
        ["MachineCode"] = "Machine Code",
        ["SelectMachine"] = "Select Machine",

        // Mold Shapes
        ["MoldShape"] = "Mold Shape",
        ["MoldShapeManagement"] = "Mold Shape Management",
        ["MoldShapeName"] = "Mold Shape Name",
        ["ShapeImage"] = "Shape Image",
        ["MoldsCount"] = "Molds Count",
        ["SelectMoldShape"] = "Select Mold Shape",

        // Molds
        ["MoldManagement"] = "Mold Management",
        ["MoldNumber"] = "Mold Number",
        ["Width"] = "Width",
        ["Height"] = "Height",
        ["TotalEyes"] = "Total Eyes",
        ["PrintedSize"] = "Printed Size",
        ["PlainSize"] = "Plain Size",

        // Cores
        ["CoreManagement"] = "Core Management",
        ["CoreName"] = "Core Name",
        ["CoreCoefficient"] = "Core Coefficient",
        ["WidthCor"] = "Core Width",
        ["HeightCor"] = "Core Height",
        // في _englishTexts أضف:
        ["Welcome"] = "Welcome to Printer Application",
        ["WelcomeMessage"] = "Comprehensive Management System for Printing Operations",
        ["ManageCores"] = "Manage Cores and Dimensions",
        ["ManageCartons"] = "Manage Cartons and Packaging",
        ["ManageKnives"] = "Manage Knives and Pricing",
        ["ManageSuppliers"] = "Manage Suppliers and Contacts",
        ["ManageRawMaterials"] = "Manage Raw Materials and Pricing",
        ["ManageProducts"] = "Manage Products and Details",
        ["ManageAdditions"] = "Manage Manufacturing Additions",
        ["ManageMachines"] = "Manage Machines and Maintenance",
        ["PleaseLoginMessage"] = "Please login to access the system",
        ["Login"] = "Login",
        ["Cartons"] = "Cartons",
        ["Knives"] = "Knives",
        ["Suppliers"] = "Suppliers",
        ["RawMaterials"] = "Raw Materials",
        ["Products"] = "Products",
        ["Additions"] = "Additions",

        // في _englishTexts:
        ["LastName"] = "Last Name",
        ["EnterLastName"] = "Enter your last name",

        // في _englishTexts أضف:
        ["TotalCartons"] = "Total Cartons",
        ["ActiveCartons"] = "Active Cartons",
        ["InactiveCartons"] = "Inactive Cartons",
        ["AverageFactor"] = "Average Factor",
        ["CartonName"] = "Carton Name",
        ["CartonFactor"] = "Carton Factor",
        ["ClearSearch"] = "Clear Search",
        ["SearchingFor"] = "Searching for",
        ["Found"] = "Found",
        ["Results"] = "result(s)",
        ["NoCartonsAvailable"] = "No Cartons Available",
        ["TryAdjustingSearch"] = "Try adjusting your search criteria",
        ["StartByAddingCarton"] = "Start by adding your first carton",
        // في _englishTexts أضف:
        ["CreateCarton"] = "Create Carton",
        ["CreateNewCarton"] = "Create New Carton",
        ["CartonInformation"] = "Carton Information",
        ["EnterCartonName"] = "Enter carton name (e.g., Standard Carton A)",
        ["CartonNameMustBeUnique"] = "Carton name must be unique",
        ["EnterCartonFactor"] = "Enter carton factor (e.g., 1.25)",
        ["CartonFactorDescription"] = "The multiplication factor for this carton type",
        ["EnterDescriptionOptional"] = "Enter description (optional)",
        ["TipsForAddingCartons"] = "Tips for Adding Cartons",
        ["UseDescriptiveNames"] = "Use descriptive names for easy identification",
        ["CartonFactorUsedInCalculations"] = "Carton factor is used in calculations (similar to core factor)",
        ["CommonFactorsRange"] = "Common factors range from 0.5 to 3.0",
        ["HigherFactorMeans"] = "Higher factor means larger/heavier cartons",

        // Print Orders
        ["PrintOrdersManagement"] = "Print Orders Management",
        ["AddNewPrintOrder"] = "Add New Print Order",
        ["SearchPrintOrdersPlaceholder"] = "Search by order number, supplier, or product",
        ["AllStatuses"] = "All Statuses",
        ["AllStages"] = "All Stages",
        ["FilterActive"] = "Filter Active",
        ["TotalOrders"] = "Total Orders",
        ["PendingOrders"] = "Pending Orders",
        ["CompletedOrders"] = "Completed Orders",
        ["InProgressOrders"] = "In Progress Orders",
        ["OrderNumber"] = "Order Number",
        ["OrderDate"] = "Order Date",
        ["ExpectedDeliveryDate"] = "Expected Delivery Date",
        ["ActualDeliveryDate"] = "Actual Delivery Date",
        ["Quantity"] = "Quantity",
        ["EnterQuantity"] = "Enter quantity",
        ["EnterOrderNumber"] = "Enter order number",
        ["OrderStatusBreakdown"] = "Order Status Breakdown",
        ["OrderStageBreakdown"] = "Order Stage Breakdown",
        ["SupplierAndProduct"] = "Supplier and Product",
        ["StatusAndStage"] = "Status and Stage",
        ["Stage"] = "Stage",
        ["SelectRollDirection"] = "Select Roll Direction",
        ["Dates"] = "Dates",
        ["PrintOrderDetails"] = "Print Order Details",
        ["SupplierInformation"] = "Supplier Information",
        ["CreatePrintOrder"] = "Create Print Order",
        ["EditPrintOrder"] = "Edit Print Order",
        ["DeletePrintOrder"] = "Delete Print Order",
        ["DeletePrintOrderConfirmation"] = "Are you sure you want to delete this print order?",
        ["ConfirmDeletePrintOrder"] = "Are you sure you want to delete this order? This action cannot be undone.",
        ["PrintOrderIsActive"] = "Print Order is Active",
        ["InactivePrintOrdersNotAvailable"] = "Inactive print orders will not be available",
        ["NoPrintOrdersFound"] = "No Print Orders Found",
        ["NoPrintOrdersAvailable"] = "No Print Orders Available",
        ["StartByAddingPrintOrder"] = "Start by adding your first print order",
        ["TipsForAddingPrintOrders"] = "Tips for Adding Print Orders",
        ["OrderNumberMustBeUnique"] = "Order number must be unique",
        ["ExpectedDeliveryDateMustBeAfterOrderDate"] = "Expected delivery date must be after order date",
        ["SelectAppropriateStatusAndStage"] = "Select appropriate status and stage for the order",
        ["RollDirectionIsOptional"] = "Roll direction is optional and can be left empty",
        ["PrintOrderStatistics"] = "Print Order Statistics",
        ["AllPrintOrders"] = "All Print Orders",
        ["OfTotal"] = "of total",
        ["NoOrders"] = "No Orders",
        ["QuickActions"] = "Quick Actions",
        ["ViewAllOrders"] = "View All Orders",
        ["CreateNewOrder"] = "Create New Order",
        ["ViewPendingOrders"] = "View Pending Orders",
        ["ViewCompletedOrders"] = "View Completed Orders",
        ["Details"] = "Details",

        // Order Status Enum
        ["Pending"] = "Pending",
        ["Ready"] = "Ready",
        ["NotPrinted"] = "Not Printed",
        ["Cancelled"] = "Cancelled",

        // Order Stage Enum
        ["Order"] = "Order",
        ["Review"] = "Review",
        ["Manufacturing"] = "Manufacturing",
        ["Printing"] = "Printing",

    };

    public LanguageService(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public string GetText(string key)
    {
        var language = GetCurrentLanguage();
        var texts = language == "ar" ? _arabicTexts : _englishTexts;

        return texts.ContainsKey(key) ? texts[key] : key;
    }

    public void SetLanguage(string language)
    {
        var session = _httpContextAccessor.HttpContext?.Session;
        if (session != null)
        {
            session.SetString(SessionKey, language);
        }
    }

    public string GetCurrentLanguage()
    {
        var session = _httpContextAccessor.HttpContext?.Session;
        if (session != null)
        {
            var language = session.GetString(SessionKey);
            return string.IsNullOrEmpty(language) ? DefaultLanguage : language;
        }
        return DefaultLanguage;
    }

    public Dictionary<string, string> GetAllTexts()
    {
        var language = GetCurrentLanguage();
        return language == "ar" ? _arabicTexts : _englishTexts;
    }
}
